### ISSUE TITLE
noexcept is not supported in Visual Studio 2013

### ISSUE THREAD

**Issue by bilke** [ufz/tclap#1]
See http://stackoverflow.com/a/18387764/80480 for a solution.

This will be fixed in VS 2015, see http://blogs.msdn.com/b/vcblog/archive/2014/11/17/c-11-14-17-features-in-vs-2015-preview.aspx

**Comment by bilke** [comment]
Fixed in 03abc3a33272.

**Comment by endJunction** [comment]
Thanks! One more reason to move to VS2015.
The solution is the same as in boost, for example.
